name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SC_VERSION: "0.7.2"
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${SC_VERSION}/shellcheck-v${SC_VERSION}.linux.x86_64.tar.xz" | tar -C /usr/local/bin -xvJ --strip-components=1 "shellcheck-v${SC_VERSION}/shellcheck"
          chmod +x /usr/local/bin/shellcheck
          shellcheck --version
      - run: shellcheck iptables-docker-filter
